export const products = [
    // Sofas
    {
        id: "1",
        title: "Modern Sofa",
        price: 899.99,
        category: "sofas",
        image: "/images/products/sofa.jpg",
        rating: { rate: 4.5, count: 120 },
        isFavorite: false,
      },
      {
        id: "2",
        title: "Leather Recliner Sofa",
        price: 1099.99,
        category: "sofas",
        image: "/images/products/leather-sofa.jpg",
        rating: { rate: 4.7, count: 85 },
        isFavorite: false,
      },
      {
        id: "3",
        title: "Velvet Chesterfield Sofa",
        price: 1299.99,
        category: "sofas",
        image: "/images/products/velvet-sofa.jpg",
        rating: { rate: 4.8, count: 98 },
        isFavorite: false,
      },
      {
        id: "4",
        title: "Contemporary Grey Sofa",
        price: 799.99,
        category: "sofas",
        image: "/images/products/grey-sofa.jpg",
        rating: { rate: 4.2, count: 75 },
        isFavorite: false,
      },
      {
        id: "5",
        title: "Corner Sectional Sofa",
        price: 1499.99,
        category: "sofas",
        image: "/images/products/sectional-sofa.jpg",
        rating: { rate: 4.6, count: 65 },
        isFavorite: false,
      },
      {
        id: "6",
        title: "Mid-Century Modern Sofa",
        price: 949.99,
        category: "sofas",
        image: "/images/products/mid-century-sofa.jpg",
        rating: { rate: 4.3, count: 110 },
        isFavorite: false,
      },
      {
        id: "7",
        title: "Convertible Futon Sofa",
        price: 599.99,
        category: "sofas",
        image: "/images/products/futon-sofa.jpg",
        rating: { rate: 4.0, count: 90 },
        isFavorite: false,
      },
      {
        id: "8",
        title: "Linen Loveseat Sofa",
        price: 699.99,
        category: "sofas",
        image: "/images/products/loveseat-sofa.jpg",
        rating: { rate: 4.1, count: 80 },
        isFavorite: false,
      },
      {
        id: "9",
        title: "Tufted Velvet Sofa",
        price: 1399.99,
        category: "sofas",
        image: "/images/products/tufted-sofa.jpg",
        rating: { rate: 4.9, count: 45 },
        isFavorite: false,
      },
      {
        id: "10",
        title: "Scandinavian Sofa",
        price: 999.99,
        category: "sofas",
        image: "/images/products/scandinavian-sofa.jpg",
        rating: { rate: 4.4, count: 70 },
        isFavorite: false,
      },
      {
        id: "11",
        title: "Double Chaise Lounge Sofa",
        price: 1599.99,
        category: "sofas",
        image: "/images/products/chaise-sofa.jpg",
        rating: { rate: 4.7, count: 55 },
        isFavorite: false,
      },
      {
        id: "12",
        title: "Classic Rolled Arm Sofa",
        price: 899.99,
        category: "sofas",
        image: "/images/products/rolled-arm-sofa.jpg",
        rating: { rate: 4.5, count: 65 },
        isFavorite: false,
      },
      {
        id: "13",
        title: "Eco-Friendly Fabric Sofa",
        price: 1049.99,
        category: "sofas",
        image: "/images/products/fabric-sofa.jpg",
        rating: { rate: 4.6, count: 75 },
        isFavorite: false,
      },
      {
        id: "14",
        title: "Luxury Italian Leather Sofa",
        price: 2199.99,
        category: "sofas",
        image: "/images/products/italian-leather-sofa.jpg",
        rating: { rate: 4.8, count: 40 },
        isFavorite: false,
      },
  
    // Beds
    {
      id: "3",
      title: "Queen Bed",
      price: 699.99,
      category: "beds",
      image: "/images/products/bed.jpg",
      rating: { rate: 4.3, count: 98 },
      isFavorite: false,
    },
    {
      id: "4",
      title: "King Bed with Storage",
      price: 899.99,
      category: "beds",
      image: "/images/products/king-bed.jpg",
      rating: { rate: 4.6, count: 112 },
      isFavorite: false,
    },
  
    // Chairs
    {
      id: "5",
      title: "Dining Chair Set",
      price: 199.99,
      category: "chairs",
      image: "/images/products/dining-chair.jpg",
      rating: { rate: 4.2, count: 76 },
      isFavorite: false,
    },
    {
      id: "6",
      title: "Office Chair",
      price: 149.99,
      category: "chairs",
      image: "/images/products/office-chair.jpg",
      rating: { rate: 4.4, count: 89 },
      isFavorite: false,
    },
  
    // Tables
    {
      id: "7",
      title: "Coffee Table",
      price: 249.99,
      category: "tables",
      image: "/images/products/coffee-table.jpg",
      rating: { rate: 4.1, count: 63 },
      isFavorite: false,
    },
    {
      id: "8",
      title: "Dining Table",
      price: 499.99,
      category: "tables",
      image: "/images/products/dining-table.jpg",
      rating: { rate: 4.5, count: 95 },
      isFavorite: false,
    },
  
    // Cabinets
    {
      id: "9",
      title: "Kitchen Cabinet",
      price: 399.99,
      category: "cabinets",
      image: "/images/products/kitchen-cabinet.jpg",
      rating: { rate: 4.3, count: 72 },
      isFavorite: false,
    },
    {
      id: "10",
      title: "Storage Cabinet",
      price: 299.99,
      category: "cabinets",
      image: "/images/products/storage-cabinet.jpg",
      rating: { rate: 4.0, count: 68 },
      isFavorite: false,
    },
  
    // Wardrobes
    {
      id: "11",
      title: "Sliding Door Wardrobe",
      price: 599.99,
      category: "wardrobes",
      image: "/images/products/wardrobe.jpg",
      rating: { rate: 4.6, count: 81 },
      isFavorite: false,
    },
    {
      id: "12",
      title: "3-Door Wardrobe",
      price: 699.99,
      category: "wardrobes",
      image: "/images/products/3-door-wardrobe.jpg",
      rating: { rate: 4.8, count: 93 },
      isFavorite: false,
    },
  
    // TV Stands
    {
      id: "13",
      title: "Wooden TV Stand",
      price: 199.99,
      category: "tv-stands",
      image: "/images/products/tv-stand.jpg",
      rating: { rate: 4.1, count: 54 },
      isFavorite: false,
    },
    {
      id: "14",
      title: "Modern Glass TV Stand",
      price: 299.99,
      category: "tv-stands",
      image: "/images/products/glass-tv-stand.jpg",
      rating: { rate: 4.3, count: 66 },
      isFavorite: false,
    },
  
    // Office Furniture
    {
      id: "15",
      title: "Office Desk",
      price: 349.99,
      category: "office-furniture",
      image: "/images/products/office-desk.jpg",
      rating: { rate: 4.4, count: 78 },
      isFavorite: false,
    },
    {
      id: "16",
      title: "Bookshelf",
      price: 199.99,
      category: "office-furniture",
      image: "/images/products/bookshelf.jpg",
      rating: { rate: 4.2, count: 65 },
      isFavorite: false,
    },
  
    // Outdoor Furniture
    {
      id: "17",
      title: "Patio Table Set",
      price: 499.99,
      category: "outdoor-furniture",
      image: "/images/products/patio-table.jpg",
      rating: { rate: 4.6, count: 84 },
      isFavorite: false,
    },
    {
      id: "18",
      title: "Lounge Chair",
      price: 299.99,
      category: "outdoor-furniture",
      image: "/images/products/lounge-chair.jpg",
      rating: { rate: 4.3, count: 58 },
      isFavorite: false,
    },
  
    // Kids' Furniture
    {
      id: "19",
      title: "Kids' Bunk Bed",
      price: 499.99,
      category: "kids-furniture",
      image: "/images/products/bunk-bed.jpg",
      rating: { rate: 4.7, count: 88 },
      isFavorite: false,
    },
    {
      id: "20",
      title: "Kids' Study Desk",
      price: 199.99,
      category: "kids-furniture",
      image: "/images/products/kids-desk.jpg",
      rating: { rate: 4.4, count: 75 },
      isFavorite: false,
    },
  ];
  